name: Update PDF Paths

on:
  push:
    paths:
      - 'doc/**'
  delete:
    paths:
      - 'doc/**'

jobs:
  update-pdf-paths:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Find DOC files
      run: |
        echo "{" > doc_paths.json
        echo "  \"courses\": [" >> doc_paths.json
        find doc/courses -name "*.docx" | sort | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >>doc_paths.json
        echo "  ]," >> doc_paths.json
        echo "  \"td\": [" >> doc_paths.json
        find doc/td -name "*.docx" | sort | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >> doc_paths.json
        echo "  ]" >> doc_paths.json
        echo "}" >> doc_paths.json

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add doc_paths.json
        git commit -m "Update DOC paths (sorted chronologically)" || echo "No changes to commit"
        git push
