name: Update Other Files

on:
  push:
    paths:
      - 'other/**'
  delete:
    paths:
      - 'other/**'  # Remove this line if you don't want to delete existing files (be cautious)

jobs:
  update-other-files:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Find Files in Other Courses and TD
      run: |
        echo "{" > other_files.json
        echo "  \"courses\": [" >> other_files.json
        find other/courses -type f ! -name "*.*" | sort | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >>other_files.json
        echo "  ]," >> other_files.json
        echo "  \"td\": [" >> other_files.json
        find other/td -type f ! -name "*.*" | sort | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >>other_files.json
        echo "  ]," >> other_files.json
        echo "  \"tp\": [" >> other_files.json
        find other/tp -type f ! -name "*.*" | sort | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >>other_files.json
        echo "  ]" >> other_files.json
        echo "}" >> other_files.json

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add other_files.json
        git commit -m "Update Other Files (sorted chronologically)" || echo "No changes to commit"
        git push