name: Update PDF Paths

on:
  push:
    paths:
      - 'pdf/**'

jobs:
  update-pdf-paths:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Find PDF files
      run: |
        echo "{" > pdf_paths.json
        echo "  \"courses\": [" >> pdf_paths.json
        find pdf/courses -name "*.pdf" | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >> pdf_paths.json
        echo "  ]," >> pdf_paths.json
        echo "  \"TD\": [" >> pdf_paths.json
        find pdf/TD -name "*.pdf" | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >> pdf_paths.json
        echo "  ]" >> pdf_paths.json
        echo "}" >> pdf_paths.json

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add pdf_paths.json
        git commit -m "Update PDF paths" || echo "No changes to commit"
        git push
