name: Update XLS Paths

on:
  push:
    paths:
      - 'xls/**'
  delete:
    paths:
      - 'xls/**'

jobs:
  update-pdf-paths:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Find XLS files
      run: |
        echo "{" > xls_paths.json
        echo "  \"courses\": [" >> xls_paths.json
        find xls/courses -name "*.xlsx" | sort | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >>xls_paths.json
        echo "  ]," >> xls_paths.json
        echo "  \"td\": [" >> xls_paths.json
        find xls/td -name "*.xlsx" | sort | sed 's/^/    "/' | sed 's/$/",/' | sed '$s/,$//' >> xls_paths.json
        echo "  ]" >> xls_paths.json
        echo "}" >> xls_paths.json

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add xls_paths.json
        git commit -m "Update XLS paths (sorted chronologically)" || echo "No changes to commit"
        git push
